### ISSUE TITLE
Cannot create MultiHeadAttention layer from config with weights

### ISSUE THREAD

**Issue by christian-steinmeyer** [keras-team/tf-keras#157]
**System information**.
- Have I written custom code (as opposed to using a stock example script provided in Keras): yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): macos Ventura 13.4.1
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 2.12
- Python version: 3.10
- Bazel version (if compiling from source):
- GPU model and memory:

**Describe the problem**.

When creating a `MultiHeadAttention` layer from config and providing weights, automatic setting of weights does not work (as in other layers).

**Describe the current behavior**.
ValueError in `set_weights` called from `_maybe_build` due to non-matching weight lengths.

**Describe the expected behavior**.
No ValueError. Weights of the layer are initialized based on the provided weights in config and then used.

**[Contributing](https://github.com/keras-team/keras/blob/master/CONTRIBUTING.md)**.

- Do you want to contribute a PR? (yes/no): yes, if someone points me in the right direction
- If yes, please read [this page](https://github.com/keras-team/keras/blob/master/CONTRIBUTING.md) for instructions
- Briefly describe your candidate solution(if contributing):

**Standalone code to reproduce the issue**.
```py
import tensorflow as tf

if __name__ == '__main__':
    mha = tf.keras.layers.MultiHeadAttention(num_heads=2, key_dim=64, name="mha")
    inputs = (tf.random.uniform((1, 2, 4)), tf.random.uniform((1, 2, 4)))
    mha(*inputs)
    weights = mha.get_weights()
    config = mha.get_config()
    config['weights'] = weights
    new_mha = tf.keras.layers.MultiHeadAttention.from_config(config)
    new_mha(*inputs)  # <-- fails
```

**Traceback**.

```
Traceback (most recent call last):
  File "<MY_SCRIPT>.py", line 11, in <module>
    new_mha(*inputs)
  File "<VIRTUAL_ENV>/lib/python3.10/site-packages/keras/src/utils/traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "<VIRTUAL_ENV>/lib/python3.10/site-packages/keras/src/engine/base_layer.py", line 1807, in set_weights
    raise ValueError(
ValueError: You called `set_weights(weights)` on layer "mha" with a weight list of length 8, but the layer was expecting 0 weights. Provided weights: [array([[[-0.02902268,  0.05308066,  0.10171321, -...
```

**Comment by tilakrayal** [comment]
I tried to execute the mentioned code with the recommended workflow sequence for Multiheadattention and observed the code was executed without issue/fail. Kindly find the gist of it [here](https://colab.research.google.com/gist/tilakrayal/3bd0dcaa03ec6cb4e4bb4ba41602ec37/untitled2417.ipynb). Thank you!
