### ISSUE TITLE
"No common supertype of ..." while loading model

### ISSUE THREAD

**Issue by ahasselbring** [keras-team/tf-keras#431]
**System information**.
- Have I written custom code (as opposed to using a stock example script provided in Keras): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Mint 21
- TensorFlow installed from (source or binary): binary (tensorflow-cpu via pipenv)
- TensorFlow version (use command below): v2.9.1-132-g18960c44ad3 2.9.2
- Python version: 3.10
- Bazel version (if compiling from source): -
- GPU model and memory: -
- Exact command to reproduce: Given the standalone code below saved as `minimal-example.py`, run `python minimal-example.py`

**Describe the problem**.

I can't load a model when passing a variable to a submodel. See the example below. [This](https://github.com/keras-team/keras/blob/r2.9/keras/saving/saved_model/load.py#L1150) explicitly tells me to "[...] file a bug if [...] being hindered by this error." Code like that worked with previous versions of TensorFlow (2.7 I think).

**Describe the current behavior**.

Loading fails with `No common supertype of TensorSpec(...) and VariableSpec(...).`

**Describe the expected behavior**.

The model is loaded without errors.

**[Contributing](https://github.com/keras-team/keras/blob/master/CONTRIBUTING.md)**.

- Do you want to contribute a PR? (yes/no): no

**Standalone code to reproduce the issue**.

```python
import tensorflow as tf

class SubModel(tf.keras.models.Model):
    def call(self, x):
        return ()  # My actual model returns something depending on x here, but even this fails.

class MainModel(tf.keras.models.Model):
    def __init__(self):
        super().__init__()
        self.sub_model = SubModel()
        self.x = tf.Variable(tf.zeros((1,)))

    def call(self, _):
        return self.sub_model(self.x)

model = MainModel()
model(())
model.save("model")
model = tf.keras.models.load_model("model")
```

**Source code / logs**.

Output of the above script:
```
Traceback (most recent call last):
  File ".../minimal-example.py", line 19, in <module>
    model = tf.keras.models.load_model("model")
  File ".../.venv/lib/python3.10/site-packages/keras/utils/traceback_utils.py", line 67, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File ".../.venv/lib/python3.10/site-packages/keras/saving/saved_model/load.py", line 1151, in common_spec
    raise TypeError(f'No common supertype of {x} and {y}.')
TypeError: No common supertype of TensorSpec(shape=(None,), dtype=tf.float32, name=None) and VariableSpec(shape=(1,), dtype=<dtype: 'float32'>, trainable=True).
```

**Comment by ThibaultDef** [comment]
By looking directly into the code, I saw that the error comes from the function `most_specific_common_supertype` (within https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/framework/type_spec.py). As I understood, I compares types between tensors. If a type is not matching between (for example one is of type `float32` and another one is of type `float16`), then the error raises.
