### ISSUE TITLE
float number in randint Python 3.12

### ISSUE THREAD

**Issue by dk222dk** [keras-team/tf-keras#803]
I noticed in the source code there are some calls of `generator.randint(1, 1e9)`  1e9 is converted to float but in python 3.12 calling float in randint causes an error

**System information**.
- Python 3.12
- tf_keras 2.17.0
- tensorflow  2.17.0

Running with env variable: TF_USE_LEGACY_KERAS=1

Simple steps to reproduce:
```
import tensorflow as tf
tf.keras.utils.set_random_seed(10)
from tensorflow.keras.initializers import VarianceScaling
vs = VarianceScaling()
vs((3, 3))
```

Error log

```
Traceback (most recent call last):
  File "/mnt/g/PycharmProjects/testing/first.py", line 8, in <module>
    vs((3, 3))
  File "/home/user/miniconda3/envs/t2/lib/python3.12/site-packages/tf_keras/src/initializers/initializers.py", line 648, in __call__
    return self._generate_init_val(shape=shape, dtype=dtype, nonce=nonce)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/miniconda3/envs/t2/lib/python3.12/site-packages/tf_keras/src/initializers/initializers.py", line 663, in _generate_init_val
    return self._random_generator.truncated_normal(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/miniconda3/envs/t2/lib/python3.12/site-packages/tf_keras/src/backend.py", line 2134, in truncated_normal
    self._maybe_init()
  File "/home/user/miniconda3/envs/t2/lib/python3.12/site-packages/tf_keras/src/backend.py", line 1976, in _maybe_init
    self._seed = self._create_seed(self._seed)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/miniconda3/envs/t2/lib/python3.12/site-packages/tf_keras/src/backend.py", line 2032, in _create_seed
    return _SEED_GENERATOR.generator.randint(1, 1e9)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/miniconda3/envs/t2/lib/python3.12/random.py", line 336, in randint
    return self.randrange(a, b+1)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/miniconda3/envs/t2/lib/python3.12/random.py", line 312, in randrange
    istop = _index(stop)
            ^^^^^^^^^^^^
TypeError: 'float' object cannot be interpreted as an integer 
```

**Comment by tilakrayal** [comment]
@dk222dk,
I tried to execute the mentioned code on both Keras2.0 & keras3.0  and observed that the code was executed without any issues/fail. Kindly find the gist of it [here](https://colab.research.google.com/gist/tilakrayal/92ffcafdcf110ac4f01386a0c688c35c/untitled2179.ipynb). Thank you!

**Comment by dk222dk** [comment]
@tilakrayal You didn't use python **3.12** this error occurs only with python **>3.12** and in previous versions you get warnings that calling randint with float is deprecated and support will be removed in next python versions

**Comment by dk222dk** [comment]
@tilakrayal are you able to create a MR with that change and release new version of tf_keras? it should be a simple change currently it's something that blocks users from using tf_keras with python 3.12 since it doesn't work with that version.

**Comment by dk222dk** [comment]
I noticed there are other test fails with python 3.12

**Comment by MartinNowak** [comment]
Mostly fixed by https://github.com/keras-team/tf-keras/commit/6f449910f216ff7455a90eb2a68e54a4d2956696
Though [it seems](https://github.com/search?q=repo%3Akeras-team%2Ftf-keras+%2Frandint%5C%28.*%2C+%5Cd%2Be%2F&type=code) like these remained → #815.
